@startuml
class Adhesions {
Encours : booléen 
Début : Date
Fin: Date
}

class Adherents{
Nom : char
Prenom : char 
Adresse : char 
Mail : char
Num_telephone : int
Date_de_naissance : Date
carte : str 
}

class Personnel{
Nom : char
Prenom : char 
Adresse : char 
Mail : char
}

class Exemplaire {
État : enum
Clé : char 
Disponibilités : char 
compteur : int 
}

Class Ressource { 
Code :int 
Titre :char
Éditeur :char
Genre : enum
Date_appartion :Date
Nb_exemplaire : int
}

class Livre {
ISBN : char
Langue : char 
Résumé: char 
}

class Film {
Synopsis: char
Langue : char 
Durée_film: time  
}

class œuvremusicale { 
Durée_oeuvre: Time
}

Class Compte_utilisateur{
Login : int
Mot_de_passe : string
}

Class Sanction{
Nb_retard
Nb_degradation 
En_sanction :Boolean 
Durée_sanction 
}

Class Emprunt_en_cours{
Durée_limite : Date
Etat_retour : enum
}

Class Contributeurs{
Rôle :char
Nom :char
Prenom :char
Date_de_naissance:Date 
Nationalité: char
}

Resource <|- œuvremusicale
Resource <|- Film
Resource <|- Livre

Adherents "1..1" - "1..1" Compte_utilisateur 
(Adherents , Compte_utilisateur ) .. Adhesions

Emprunt_en_cours "0..1" - "1..1" Exemplaire
Contributeurs "1..*" - "1..*" Ressource
Adherents "1..1" - "0..Nmax" Emprunt_en_cours 
(Adherents , Emprunt_en_cours ) .. Sanction

Compte_utilisateur "1..1" - "1..1" Personnel
Exemplaire "1..*" - "1..1" Ressource
@enduml
